name: Lint

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:

    runs-on: ubuntu-22.04

    name: Lint

    steps:
    - uses: actions/checkout@v3

    - name: pre-commit cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: lint-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          lint-pre-commit-

    - name: Set up Python
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: "3.x"
        cache: pip
        cache-dependency-path: "setup.py"

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Install dependencies
      run: |
        python3 -m pip install --index-url 'https://:2023-09-15T13:56:57.712378Z@time-machines-pypi.sealsecurity.io/' -U pip
        python3 -m pip install --index-url 'https://:2023-09-15T13:56:57.712378Z@time-machines-pypi.sealsecurity.io/' -U tox

    - name: Lint
      run: tox -e lint
      env:
        PRE_COMMIT_COLOR: always
